#!/usr/bin/env julia
# config_manager.jl — YAML/TOML 設定管理を Julia で実行
# comfyServerConfig.ts の YAML パース・生成を置き換え

using JSON3, YAML, TOML, Dates

"""YAML設定ファイルを読み込んでJSONで出力"""
function read_yaml_config(filepath::String)::Dict{String,Any}
    if !isfile(filepath)
        return Dict{String,Any}("error" => "not_found", "path" => filepath)
    end

    try
        data = YAML.load_file(filepath)
        return Dict{String,Any}("status" => "success", "data" => data, "path" => filepath)
    catch e
        return Dict{String,Any}("status" => "error", "error" => string(e), "path" => filepath)
    end
end

"""YAML設定ファイルを書き込み"""
function write_yaml_config(filepath::String, data::Dict)::Dict{String,Any}
    try
        header = "# ComfyUI extra_model_paths.yaml (generated by Julia)\n# $(Dates.now())\n"
        open(filepath, "w") do io
            write(io, header)
            YAML.write(io, data)
        end
        return Dict{String,Any}("status" => "success", "path" => filepath)
    catch e
        return Dict{String,Any}("status" => "error", "error" => string(e))
    end
end

"""TOML設定ファイルを読み込み"""
function read_toml_config(filepath::String)::Dict{String,Any}
    if !isfile(filepath)
        return Dict{String,Any}("error" => "not_found", "path" => filepath)
    end

    try
        data = TOML.parsefile(filepath)
        return Dict{String,Any}("status" => "success", "data" => data, "path" => filepath)
    catch e
        return Dict{String,Any}("status" => "error", "error" => string(e), "path" => filepath)
    end
end

"""TOML設定ファイルを書き込み"""
function write_toml_config(filepath::String, data::Dict)::Dict{String,Any}
    try
        open(filepath, "w") do io
            TOML.print(io, data)
        end
        return Dict{String,Any}("status" => "success", "path" => filepath)
    catch e
        return Dict{String,Any}("status" => "error", "error" => string(e))
    end
end

"""base_path を YAML 設定から抽出"""
function read_base_path(filepath::String)::Dict{String,Any}
    result = read_yaml_config(filepath)
    if haskey(result, "error")
        return result
    end

    data = result["data"]
    base_path = nothing

    # 新形式: comfyui_desktop.base_path
    if haskey(data, "comfyui_desktop") && isa(data["comfyui_desktop"], Dict) && haskey(data["comfyui_desktop"], "base_path")
        base_path = data["comfyui_desktop"]["base_path"]
    # レガシー形式: comfyui.base_path
    elseif haskey(data, "comfyui") && isa(data["comfyui"], Dict) && haskey(data["comfyui"], "base_path")
        base_path = data["comfyui"]["base_path"]
    end

    if base_path === nothing || !isa(base_path, AbstractString)
        return Dict{String,Any}("status" => "invalid", "path" => filepath)
    end

    return Dict{String,Any}("status" => "success", "base_path" => base_path)
end

"""モデルパス設定を生成"""
function generate_model_paths(base_path::String)::Dict{String,Any}
    known_keys = [
        "checkpoints", "classifiers", "clip", "clip_vision", "configs",
        "controlnet", "diffusers", "diffusion_models", "embeddings",
        "gligen", "hypernetworks", "loras", "photomaker", "style_models",
        "text_encoders", "unet", "upscale_models", "vae", "vae_approx",
    ]

    paths = Dict{String,String}()
    for key in known_keys
        paths[key] = joinpath(base_path, "models", key, "")
    end

    return Dict{String,Any}(
        "comfyui_desktop" => Dict{String,Any}(
            "is_default" => "true",
            "custom_nodes" => "custom_nodes/",
            "download_model_base" => "models",
            "base_path" => base_path,
            paths...
        )
    )
end

"""設定のバリデーション"""
function validate_config(filepath::String)::Dict{String,Any}
    issues = String[]

    if !isfile(filepath)
        push!(issues, "config_file_not_found")
        return Dict{String,Any}("valid" => false, "issues" => issues)
    end

    try
        data = YAML.load_file(filepath)

        if !isa(data, Dict)
            push!(issues, "invalid_yaml_structure")
        else
            # base_path チェック
            bp = nothing
            if haskey(data, "comfyui_desktop") && isa(data["comfyui_desktop"], Dict)
                bp = get(data["comfyui_desktop"], "base_path", nothing)
            end
            if bp === nothing
                push!(issues, "missing_base_path")
            elseif !isdir(bp)
                push!(issues, "base_path_not_accessible: $bp")
            end
        end
    catch e
        push!(issues, "yaml_parse_error: $(string(e))")
    end

    return Dict{String,Any}("valid" => isempty(issues), "issues" => issues)
end

function main()
    if length(ARGS) < 1
        println(JSON3.write(Dict("error" => "usage: config_manager.jl <command> [args...]")))
        exit(1)
    end

    command = ARGS[1]
    result = if command == "read" && length(ARGS) >= 2
        read_yaml_config(ARGS[2])
    elseif command == "read-base-path" && length(ARGS) >= 2
        read_base_path(ARGS[2])
    elseif command == "validate" && length(ARGS) >= 2
        validate_config(ARGS[2])
    elseif command == "generate-model-paths" && length(ARGS) >= 2
        generate_model_paths(ARGS[2])
    elseif command == "read-toml" && length(ARGS) >= 2
        read_toml_config(ARGS[2])
    else
        Dict{String,Any}("error" => "unknown command: $command")
    end

    println(JSON3.write(result))
end

main()
